export const ACTION_TASK = {
    ADD:  'ADD_TASK',
    UPDATE: 'UPDATE_TASK'
};

export const ACTION_CATEGORY = {
    ADD: 'ADD_CATEGORY',
    REMOVE: 'REMOVE_CATEGORY',
    UPDATE: 'RENAME_CATEGORY',
    TRANSFER: 'ACTIVE_CATEGORY'
};

export const ACTION_ACTIVE = {
    UPDATE_SELECT: "UPDATE_SELECT",
    UPDATE__ACTIVE: "UPDATE_ACTIVE",
    UPDATE_TRANSFER: 'UPDATE_TRANSFER'
};